from fishtest.rundb import RunDb

conversions = [
    {"new_name": "NormanRKN", "old_name": "Norman_RKN"},
    {"new_name": "nicorkn", "old_name": "nico-rkn"},
    {"new_name": "SharafDG", "old_name": "Sharaf_DG"},
    {"new_name": "PatrickG", "old_name": "Patrick_G"},
    {"new_name": "ThomasAAnderson", "old_name": "Thomas A. Anderson"},
    {"new_name": "wajitcflrrcom", "old_name": "wajit@cfl.rr.com"},
    {"new_name": "trebleraosx", "old_name": "treblera_os_x"},
    {"new_name": "joseolv", "old_name": "jose-olv"},
    {"new_name": "hongzhicheng", "old_name": "hongzhi_cheng"},
    {"new_name": "bkingUS", "old_name": "bking_US"},
    {"new_name": "TomUdo", "old_name": "Tom_Udo"},
    {"new_name": "A1405thomas", "old_name": "1405thomas"},
    {"new_name": "teamoh", "old_name": "team-oh"},
    {"new_name": "chessnetpl", "old_name": "chessnet_pl"},
    {"new_name": "jenssw", "old_name": "jens-sw"},
    {"new_name": "A12k", "old_name": "12k"},
    {"new_name": "RonBritvich", "old_name": "Ron Britvich"},
    {"new_name": "Darkwizzie", "old_name": "Dark_wizzie"},
    {"new_name": "DarkwizzieA", "old_name": "Darkwizzie"},
    {"new_name": "EugenKotlov", "old_name": "Eugen_Kotlov"},
    {"new_name": "CheshireCat", "old_name": "Cheshire_Cat"},
    {"new_name": "cheshirecat", "old_name": "cheshire_cat"},
    {"new_name": "ASP1963", "old_name": "ASP_1963"},
    {"new_name": "npersson", "old_name": "n_persson"},
    {"new_name": "atanashristev", "old_name": "atanas_hristev"},
    {"new_name": "GurcanUckardes", "old_name": "Gurcan_Uckardes"},
    {"new_name": "FabioMQC", "old_name": "Fabio_MQC"},
    {"new_name": "bookfan", "old_name": "book_fan"},
    {"new_name": "alfagammaalfa", "old_name": "alfagamma.alfa"},
    {"new_name": "francescodallacqua", "old_name": "francesco.dallacqua"},
    {"new_name": "cdfishtest", "old_name": "cd_fishtest"},
    {"new_name": "crunchytv", "old_name": "crunchy_tv"},
    {"new_name": "ErkanYilmaz", "old_name": "Erkan_Yilmaz"},
    {"new_name": "saileshakkaraju", "old_name": "sailesh_akkaraju"},
    {"new_name": "NoPasaran", "old_name": "No_Pasaran"},
    {"new_name": "SriramGirish", "old_name": "Sriram Girish"},
    {"new_name": "SriramGirishTheJd", "old_name": "Sriram Girish - The Jd"},
    {"new_name": "MikeFlex", "old_name": "Mike_Flex"},
    {"new_name": "qoocharlycai", "old_name": "qoo_charly_cai"},
    {"new_name": "MenAFadel", "old_name": "MenA_Fadel"},
    {"new_name": "IvanIvec", "old_name": "Ivan Ivec"},
    {"new_name": "YHWHA", "old_name": "Y.H.W.H"},
    {"new_name": "chessxyz", "old_name": "chess_xyz"},
    {"new_name": "A2bad4me", "old_name": "2bad4me"},
    {"new_name": "Wernerj", "old_name": "Werner j."},
    {"new_name": "DualE52660v3", "old_name": "Dual E5-2660 v3"},
    {"new_name": "c48xlarge", "old_name": "c4.8xlarge"},
    {"new_name": "magnilinux", "old_name": "magni_linux"},
    {"new_name": "dankobumAMD", "old_name": "dankobum_AMD"},
    {"new_name": "CSUDynasty", "old_name": "CSU_Dynasty"},
    {"new_name": "MxTriX", "old_name": "MxTriX_"},
    {"new_name": "TukTuk", "old_name": "Tuk_Tuk"},
    {"new_name": "newuser", "old_name": "new_user"},
    {"new_name": "fbvsf", "old_name": "fbv-sf"},
    {"new_name": "horstprack", "old_name": "horst.prack"},
    {"new_name": "A31m059", "old_name": "31m059"},
    {"new_name": "masteroogway", "old_name": "master_oogway"},
    {"new_name": "A1234", "old_name": "1234"},
    {"new_name": "hyperbolictom", "old_name": "hyperbolic.tom"},
    {"new_name": "Z2016", "old_name": "Z-2016"},
    {"new_name": "stockfishpoolworker", "old_name": "stockfish_pool_worker"},
    {"new_name": "mrfritz", "old_name": "mr.fritz"},
    {"new_name": "NikolayIT", "old_name": "Nikolay.IT"},
    {"new_name": "TraugottStreicher", "old_name": "Traugott.Streicher"},
    {"new_name": "eva42linux", "old_name": "eva42_linux"},
    {"new_name": "markososic", "old_name": "marko.sosic"},
    {"new_name": "alialzhrani", "old_name": "ali-al-zhrani"},
    {"new_name": "AMDUsersNeoGen", "old_name": "[AMD Users] NeoGen"},
    {"new_name": "A0x539", "old_name": "0x539"},
    {"new_name": "wumovobatty7302", "old_name": "wumovobatty-7302"},
    {"new_name": "A8540610765287", "old_name": "8540610765287"},
    {"new_name": "MLahoz", "old_name": "M_Lahoz"},
    {"new_name": "notazombie", "old_name": "not_a_zombie"},
    {"new_name": "RonanH", "old_name": "Ronan_H"},
    {"new_name": "ZeroGravitas", "old_name": "Zero-Gravitas"},
    {"new_name": "Pkingcda", "old_name": "Pking_cda"},
    {"new_name": "alanr", "old_name": "alan r"},
    {"new_name": "AndrewGrant", "old_name": "Andrew Grant"},
    {"new_name": "A4skinFeelsGreat", "old_name": "4skinFeelsGreat"},
    {"new_name": "rohitrajiit", "old_name": "rohitraj_iit"},
    {
        "new_name": "Slapfishforgottenpassword",
        "old_name": "Slapfish_forgotten_password",
    },
    {"new_name": "Allonautilus4core", "old_name": "Allonautilus_4core"},
    {"new_name": "samuelH", "old_name": "samuel H."},
    {"new_name": "primegriduser", "old_name": "primegrid_user"},
    {"new_name": "AdrianSchmidt123", "old_name": "Adrian.Schmidt123"},
    {"new_name": "ChessDBCNWorkerPool", "old_name": "ChessDB_CN_WorkerPool"},
    {"new_name": "A890403", "old_name": "890403"},
    {"new_name": "eromac", "old_name": "ero-mac"},
    {"new_name": "SamuelH", "old_name": "Samuel H."},
    {"new_name": "A8bittrex", "old_name": "8bittrex"},
    {"new_name": "A0xB00B1ES", "old_name": "0xB00B1ES"},
    {"new_name": "A0x3C33", "old_name": "0x3C33"},
    {"new_name": "A00026980610", "old_name": "00026980610"},
    {"new_name": "A1400steven", "old_name": "1400steven"},
    {"new_name": "A5Y456465", "old_name": "5Y456465"},
    {"new_name": "A53142", "old_name": "53142"},
    {"new_name": "A5t0ckf15hTr4in3r", "old_name": "5t0ckf15hTr4in3r"},
    {"new_name": "A5cos5", "old_name": "5cos5"},
    {"new_name": "A1path1", "old_name": "1path1"},
    {"new_name": "A1thGrader", "old_name": "1thGrader"},
    {"new_name": "A3cho", "old_name": "3cho"},
    {"new_name": "A85", "old_name": "85"},
    {"new_name": "A1A", "old_name": "1A"},
    {"new_name": "A4150a", "old_name": "4150a"},
    {"new_name": "A8bitPuffin", "old_name": "8bitPuffin"},
]

userdb = RunDb().userdb

for c in conversions:
    old_name = c["old_name"]
    new_name = c["new_name"]
    user = userdb.get_user(old_name)
    if user is None:
        print(f"User {old_name} not found...")
        continue
    user["username"] = new_name
    print(f"Converting {old_name} to {new_name}...")
    userdb.save_user(user)
