# This is a basic workflow for fishtest

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use MongoDb
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
      
      # Use Python
      - name: Set up Python
        uses: actions/setup-python@v2

      # And run the tests
      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Run server tests
        run: |
          ./test_server.sh

      - name: Run worker tests
        run: |
          ./test_worker.sh
